In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
plt.xlabel('Area (sq ft)')
plt.ylabel('Price (USD)')
plt.scatter(df.area, df.price, color='red', marker='+');

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [5]:
model.predict([[3300]])

array([628715.75342466])

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
plt.xlabel('Area (sq ft)')
plt.ylabel('Price (USD)')
plt.scatter(df.area, df.price, color='red', marker='+')
plt.plot(df.area, model.predict(df[['area']]), color='blue');

In [9]:
test_data = pd.read_csv('https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/areas.csv')
test_data

area
0   1000
1   1500
2   2300
3   3540
4   4120
5   4560
6   5490
7   3460
8   4750
9   2300
10  9000
11  8600
12  7100

In [10]:
model.predict(test_data)

array([ 316404.10958904,  384297.94520548,  492928.08219178,
        661304.79452055,  740061.64383562,  799808.21917808,
        926090.75342466,  650441.78082192,  825607.87671233,
        492928.08219178, 1402705.47945205, 1348390.4109589 ,
       1144708.90410959])