In [2]:
import numpy as np

In [4]:
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [7]:
Lam, V = np.linalg.eig(A)
Lam, V

(array([-0.37228132,  5.37228132]),
 array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [8]:
V[:, 0]

array([-0.82456484,  0.56576746])

In [11]:
V[:, 0] * Lam[0]

array([ 0.30697009, -0.21062466])

In [10]:
A.dot(V[:, 0])

array([ 0.30697009, -0.21062466])

In [16]:
T = Lam * V
T

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [21]:
A @ V

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])