In [1]:
import numpy as np

x1 + x2 = 2200
   
1.5 x1 + 4 x2 = 5050

A x = b

x = inv(a) b

In [2]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

A, b

(array([[1. , 1. ],
        [1.5, 4. ]]),
 array([2200, 5050]))

In [3]:
# Slower
np.linalg.inv(A).dot(b)

array([1500.,  700.])

In [4]:
# Better
np.linalg.solve(A, b)

array([1500.,  700.])