In [1]:
import numpy as np

In [5]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
10 * np.ones((2, 3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.random.random()

0.6797227372507814

In [15]:
np.random.random((2, 3))

array([[0.72811882, 0.98911906, 0.57266567],
       [0.60028711, 0.78129699, 0.93604267]])