In [1]:
import numpy as np

In [16]:
P = np.array([[1, 2], [2, 1]])
P

array([[1, 2],
       [2, 1]])

In [17]:
T = np.array([[2, 1], [-1, 2]])
T

array([[ 2,  1],
       [-1,  2]])

In [18]:
T.dot(P)

array([[4, 5],
       [3, 0]])

In [20]:
Lam, V = np.linalg.eig(P)
Lam, V

(array([ 3., -1.]),
 array([[ 0.70710678, -0.70710678],
        [ 0.70710678,  0.70710678]]))

In [21]:
Lam * V

array([[ 2.12132034,  0.70710678],
       [ 2.12132034, -0.70710678]])

In [22]:
P @ V

array([[ 2.12132034,  0.70710678],
       [ 2.12132034, -0.70710678]])